### ISSUE TITLE
Script Uses Deprecated MDM Command Jamf Pro API Endpoint

### ISSUE THREAD

**Issue by moose-juice** [chrisgzim/Jamf-API-Recovery-Lock-by-Group#11] opened 2024-10-22 19:03 UTC
Lines 489 & 508 use the deprecated /api/preview/mdm/commands endpoint, which is likely the cause of the script failing to collect management IDs for computers.

Script could be updated to use new API endpoint which is https://yourServer.jamfcloud.com/api/v2/mdm/commands

See https://developer.jamf.com/jamf-pro/reference/post_v2-mdm-commands for more details. 

Will update again after I update my local repo with this change.

**Comment by joshnovotny** [comment] 2024-10-25 17:32
I changed those two lines on my local copy but still not finding the serials/MGMT IDs.

**Comment by chrisgzim** [comment] 2024-10-27 14:48
Hey everyone! Thank you for the feedback. I'm going to rewrite the management Id logic. Instead of trying to grab all of them at once, I will instead grab them right before sending the remote lock. 

I will get something committed to dev on Monday at the latest. Apologies for the delay and inconvenience

**Comment by chrisgzim** [comment] 2024-10-27 17:16
Okay! I have updated the endpoints. . . but I found out what is breaking this workflow now. 

The endpoint for the computers-preview does give me a management id value for computers, but no longer gives a serial number. . . so that is fun. 

I have updated the endpoints in my sandbox, but I will need to refactor how I am matching serials to management ids moving forward. More than likely, I could just use an advanced search to pull of the data -- it would limit the amount of api calls. (but would require extra configuration on the instance for you to setup -- albeit minimum amount of work.) OR -- my other proposed fix -- I just run a call for each computer and grab the management id on the fly. 

I will create one for each path, and post them on the dev branch. Again, my bad that I didn't do more on this earlier. Thank you again for reaching on this.

**Comment by chrisgzim** [comment] 2024-10-27 17:47
Lazy fix created here: https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/development/swiftdialog_jproapilock_lazy.sh

Check it out. I needed to update the endpoints -- as @moose-juice correctly pointed out. I also needed to add the HARDWARE section to the computers-inventory endpoint, and I needed to update my python script. I HOPE this yields some better results for you all. 

I will commit to also making: 

1. A version with the advanced search lookup -- as that would be a lot less data to parse and may yield some better results 
2. A version that grabs the management id ad-hoc (which would result in more API calls.) 

I will also put in a feature request for some better RSQL support in the API for the computers-inventory as that does not appear to be working as intended.

**Comment by moose-juice** [comment] 2024-10-28 20:41
Thanks @chrisgzim the "lazy" fix seems to have worked as expected. Appreciate the quick turnaround.

Enhancements sound great. Would also love a feature to set a 'kill' time in the script to stop it from running outside or our change windows.

One more suggestion: I think you can remove the python dependency by using jq to parse the incoming JSON into a CSV. jq is supposed to be included in macOS 15, so this would potentially enable your script to work without any additional dependencies.

I started work on replacing the Python with JQ before I noticed your update this morning.

**Comment by chrisgzim** [comment] 2024-10-28 21:14
Hey @moose-juice. Would love to hear more about this "kill" time.  I am not sure I am following. 

I did find there isn't an option to use an advanced search to post the managementID criteria, which leaves me with just option 2 for another workflow. 

I am building that out as we speak to see if there is a preferred option of running this. 

For now, I am going to go ahead and merge the "lazy" fix to the production script. (And get rid of the legacy script as well.) 

I will play around with jq, if the parsing works like the python script I will use it. I also hope to add a way to save creds to the login keychain so that you don't have to put in your user each time you run it as well. 

Going to close this issue EOD tomorrow once the merging has completed and we can put together another issue for the Feature Request(s)

**Comment by chrisgzim** [comment] 2024-10-30 19:02
"Lazy Fix" has been pushed to the main branch: https://github.com/chrisgzim/Jamf-API-Recovery-Lock-by-Group/blob/main/swiftdialog_jproapilock.sh. 

Going to work on the on-demand management ids workflow next and test out jq on macOS 15 machines! 

Thank you everyone for your feedback on this!

**Closed by chrisgzim** 2024-10-30 19:02 UTC
